package com.frost23z.a30daysapp.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object ColorScheme {
    val lightScheme = lightColorScheme(
        primary = Color(0xFF1D6D00),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFF55B136),
        onPrimaryContainer = Color(0xFF021400),
        secondary = Color(0xFF416832),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFC4F1AD),
        onSecondaryContainer = Color(0xFF2C521F),
        tertiary = Color(0xFF00677E),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFF29ABCC),
        onTertiaryContainer = Color(0xFF001219),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF6FBED),
        onBackground = Color(0xFF181D14),
        surface = Color(0xFFF6FBED),
        onSurface = Color(0xFF181D14),
        surfaceVariant = Color(0xFFDBE6D0),
        onSurfaceVariant = Color(0xFF404A3A),
        outline = Color(0xFF707A68),
        outlineVariant = Color(0xFFBFCAB5),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF2C3228),
        inverseOnSurface = Color(0xFFEDF3E4),
        inversePrimary = Color(0xFF7DDD5C),
        surfaceDim = Color(0xFFD6DCCE),
        surfaceBright = Color(0xFFF6FBED),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF0F6E7),
        surfaceContainer = Color(0xFFEAF0E1),
        surfaceContainerHigh = Color(0xFFE4EADC),
        surfaceContainerHighest = Color(0xFFDFE5D6)
    )

    val darkScheme = darkColorScheme(
        primary = Color(0xFF7DDD5C),
        onPrimary = Color(0xFF0B3900),
        primaryContainer = Color(0xFF298607),
        onPrimaryContainer = Color(0xFFFFFFFF),
        secondary = Color(0xFFA6D391),
        onSecondary = Color(0xFF133807),
        secondaryContainer = Color(0xFF234816),
        onSecondaryContainer = Color(0xFFB4E19E),
        tertiary = Color(0xFF61D5F7),
        onTertiary = Color(0xFF003542),
        tertiaryContainer = Color(0xFF007F9A),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF0F150D),
        onBackground = Color(0xFFDFE5D6),
        surface = Color(0xFF0F150D),
        onSurface = Color(0xFFDFE5D6),
        surfaceVariant = Color(0xFF404A3A),
        onSurfaceVariant = Color(0xFFBFCAB5),
        outline = Color(0xFF899481),
        outlineVariant = Color(0xFF404A3A),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFDFE5D6),
        inverseOnSurface = Color(0xFF2C3228),
        inversePrimary = Color(0xFF1D6D00),
        surfaceDim = Color(0xFF0F150D),
        surfaceBright = Color(0xFF353B31),
        surfaceContainerLowest = Color(0xFF0A1008),
        surfaceContainerLow = Color(0xFF181D14),
        surfaceContainer = Color(0xFF1C2118),
        surfaceContainerHigh = Color(0xFF262C22),
        surfaceContainerHighest = Color(0xFF31372D),
    )
}